baseurl = "https://urbanrail.kyiv.group/news"
languageCode = "uk-ua"
defaultContentLanguage = "uk"
publishDir = "../../static/root/news"

# Add it only if you keep the theme in the `themes` directory.
# Remove it if you use the theme as a remote Hugo Module.
paginate = 5

disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "blue"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 4

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option you don't have to put the `cover` param in a front-matter.
  autoCover = true

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = false

  # set a custom favicon (default is a `themeColor` square)
  favicon = "/favicon.ico"

  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  # set all headings to their default size (depending on browser settings)
  # oneHeadingSize = true # default

  # whether to show a page's estimated reading time
  # readingTime = false # default

  # whether to show a table of contents
  # can be overridden in a page's front-matter
  # Toc = false # default

  # set title for the table of contents
  # can be overridden in a page's front-matter
  # TocTitle = "Table of Contents" # default


[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = "oryba"
  site = "https://urbanrail.oryba.dev"

[permalinks]
  posts = "/posts/:slug/"

[languages]
  [languages.uk]
    languageName = "Українська"
    title = "Розклад київської міської електрички – блог"
    subtitle = "Оновлення та роздуми стосовно київської міської електрички від автора цього сайту з розкладом"
    owner = "@oryba"
    keywords = "київська міська електричка розклад руху станції кільцева"
    copyright = "@oryba"
    menuMore = "Більше"
    readMore = "Читати далі"
    readOtherPosts = "Інші новини"
    newerPosts = "Новіші записи"
    olderPosts = "Старіші записи"
    missingContentMessage = "Сторінку не знайдено..."
    missingBackButtonLabel = "Назад на головну"
    minuteReadingTime = "хв на прочитання"
    words = "слів"

    [languages.uk.params.logo]
      logoText = "Підпільний блог розкладу київської міської електрички"
      logoHomeLink = "/news"

    [languages.uk.menu]
      [[languages.uk.menu.main]]
        identifier = "a-home"
        name = "Розклад"
        weight = 1
        url = "https://urbanrail.oryba.dev"
      [[languages.uk.menu.main]]
        identifier = "#community"
        name = "Спільнота"
        weight = 2
        url = "https://t.me/urbanrail"
        NewTab = true
      [[languages.uk.menu.main]]
        identifier = "#api"
        name = "API"
        weight = 3
        url = "https://urbanrail.oryba.dev/docs"
      [[languages.uk.menu.main]]
        identifier = "#code"
        name = "Код"
        weight = 4
        url = "https://github.com/oryba/urbanrail"
        newtab = true
